services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "127.0.0.1:5000:5000"
    command: mlflow ui --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0
    volumes:
      - ./mlflow.db:/mlflow.db
